name: Add Pull Requests to Project Board
'on':
  - pull_request
jobs:
  add:
    name: Add to Board
    runs-on: macos-latest
    timeout-minutes: 2
    steps:
      - name: GitHub Project Board Automation
        uses: pritishvaidya/github-project-board-automation@0.0.1.3
        with:
          project: Test Board
          column: In progress
          token: ${{ secrets.GHPROJECT_TOKEN }}
