name: Add Pull Requests to Project Board
'on':
  - pull_request
jobs:
  add:
    name: Cancel Previous Runs
    runs-on: macos-latest
    timeout-minutes: 2
    steps:
      - name: GitHub Project Board Automation
        uses: pritishvaidya/github-project-board-automation@0.0.1
        with:
          project: Test Board
          column: In progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}
